version: '3'

services:
  angular:
    hostname: angular
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - APP_NAME
    volumes:
      - ./${APP_NAME}/${PATH_SRC}:/app/src
      - ${PATH_BUILD}:/app/dist
      - ./${APP_NAME}/${PATH_E2E}:/app/e2e
    ports:
      - ${SERVE_PORT}:4200

